#pragma once

#include <string>
#include <vector>

#include <glm/vec4.hpp>

struct app_config
{
    std::string default_track;
    std::string library_path;
    char play_pause_key;
    char quit_key;
    char nav_up_key;
    char nav_down_key;
    char nav_left_key;
    char nav_right_key;
    bool use_arrow_keys;
    bool enable_online_art;
    char search_key;
    bool auto_resume_playback;
    bool safe_mode;
    glm::vec4 browser_normal_fg;
    glm::vec4 browser_selected_fg;
    glm::vec4 browser_selected_bg;
    glm::vec4 browser_inactive_fg;
    glm::vec4 browser_inactive_bg;
    glm::vec4 ui_box_fg;
    glm::vec4 ui_text_fg;
    glm::vec4 rice_colour;
    glm::vec4 rice_background_tl;
    glm::vec4 rice_background_tr;
    glm::vec4 rice_background_bl;
    glm::vec4 rice_background_br;
    bool rice_draw_art;
    std::vector<std::string> rice_art;
    bool draw_grid_canvas;
    int grid_spacing_x;
    int grid_spacing_y;
    int grid_label_every;
    glm::vec4 grid_background_tl;
    glm::vec4 grid_background_tr;
    glm::vec4 grid_background_bl;
    glm::vec4 grid_background_br;
    glm::vec4 grid_line_colour;
    glm::vec4 spectrum_colour_low;
    glm::vec4 spectrum_colour_high;
    float spectrum_particle_threshold;
    float spectrum_juice_multiplier;
    glm::vec4 scrubber_colour_low;
    glm::vec4 scrubber_colour_high;
    float particle_angle_bias;
    int metadata_max_width;
    int metadata_origin_x;
    int metadata_origin_y;
    int metadata_width;
    int metadata_height;
    int spectrum_origin_x;
    int spectrum_origin_y;
    int spectrum_width;
    int spectrum_height;
    int queue_origin_x;
    int queue_origin_y;
    int queue_width;
    int queue_height;
    int scrubber_origin_x;
    int scrubber_origin_y;
    int scrubber_width;
    int scrubber_height;
    int col_width_artist;
    int col_width_album;
    int col_width_song;
    int art_width_chars;
    int art_height_chars;
    int browser_padding;
    int target_refresh_rate;
    int listen_port;
};

app_config load_config(const std::string& path);
