# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  agmp_config = debug

else ifeq ($(config),release)
  agmp_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := agmp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

agmp:
ifneq (,$(agmp_config))
	@echo "==== Building agmp ($(agmp_config)) ===="
	@${MAKE} --no-print-directory -C . -f agmp.make config=$(agmp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f agmp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   agmp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"